###########################
#       DoorsReloaded     #
###########################

# written by mfnalex / JEFF Media GbR

# Also open both doors when one door gets powered by redstone.
# Note: if both doors are powered and only signal gets cut, only one door will close (like in vanilla)
check-for-redstone: true


###########################
#         Knocking        #
###########################

# When enabled, players can knock on doors using left-click.
# They need the permission "doorsreloaded.knock" which is given to all players by default
allow-knocking: true

# When true, players can only knock while sneaking
knocking-requires-shift: false

# Settings for the knocking sound
sound-knock-iron: ENTITY_ZOMBIE_ATTACK_IRON_DOOR
sound-knock-wood: ITEM_SHIELD_BLOCK
sound-knock-volume: 1.0
sound-knock-pitch: 1.0
sound-knock-category: BLOCKS

###########################
#           Misc          #
###########################

# Should we check for updates?
# When enabled, a message is printed in the console if a new version has
# been found, and OPs will be notified when they join the server.
# When set to true, we will check for updates on startup and every X hours
# When set to on-startup, we will only check on startup
# When set to false, don't check for updates
check-for-updates: true

# When check-for-updates is true, AngelChest will check every X hours
check-interval: 4

# Debug mode
debug: false

# NEVER CHANGE THE VALUES BELOW!
plugin-version: ${project.version}
config-version: ${config.version}